# ENV variables required:
# TARGET_ENV
# NOTEBOOKS_FOLDER
#
# (See .env and change them !)
#
version: '3.8'

services:

    api:
        build:
          dockerfile: ./docker/Dockerfile
          context: .
          target: ${TARGET_ENV:?Target Environment Missing}
        image: api-template-server
        ports:
          - 8080:8080
        volumes:
          - ./app:/app
        command: uvicorn main:app --reload --port=8080 --host="0.0.0.0"
        restart: unless-stopped
        stdin_open: true
        tty: true
    notebook:
        image: api-template-server
        depends_on:
          - api
        ports:
          - 8888:8888
        volumes:
          - ${NOTEBOOKS_FOLDER}:/app/notebooks
        command: jupyter notebook --no-browser --allow-root --NotebookApp.token='' --port=8888 --ip="0.0.0.0"
